spring:
  application: name=eat

  datasource:
    url: jdbc:mariadb://localhost:3306/living_alone
    username: sa
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  messages:
    basename: messages, errors

  mail:
    host: smtp.gmail.com
    port: 587
    username: 0907john24@gmail.com
    # 구글 보안 코드는 커밋 시 제거
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind:

recipe:
  dir: C:/Users/user/Desktop/project/file/
ingredient:
  dir: C:/Users/user/Desktop/project/ingredients/

chatbot:
  api:
    url: "https://api.openai.com/v1/chat/completions"
    # ChatGPT API Key는 커밋 시 제거
    key: ""

# 농산물유통정보 KAMIS api
# Key, ID는 커밋 시 제거
kamis.api.key: ""
kamis.api.id: ""
kamis.api.url: "http://www.kamis.or.kr/service/price/xml.do?action=dailySalesList&p_returntype=json"