spring:
  application:
    name=eat

  datasource:
    url: jdbc:mariadb://localhost:3306/living_alone
    username: sa
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages, errors

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file:
  dir: C:/Users/user/Desktop/living_alone_eat/eat/file/
